# Generated by Django 3.2.8 on 2021-11-08 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shot_address',
            new_name='shop_address',
        ),
    ]
