# Generated by Django 3.2.8 on 2021-11-13 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_shot_address_shop_shop_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='orders.shop'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.shop'),
        ),
        migrations.AlterField(
            model_name='orderfoodlist',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_food_lists', to='orders.order'),
        ),
    ]
